// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"crypto/rsa"
	"fmt"
	"pps-services-tokopedia/internal/config"
	"pps-services-tokopedia/internal/delivery/http"
	"pps-services-tokopedia/internal/domain"
	"pps-services-tokopedia/internal/repository"
	"pps-services-tokopedia/internal/service"
	"pps-services-tokopedia/internal/usecase"
	"pps-services-tokopedia/internal/utils"

	"github.com/gofiber/fiber/v2"
	"github.com/google/wire"
)

// Injectors from wire.go:

// InitializeApp creates and wires up the entire application
func InitializeApp() (*AppContainer, error) {
	app := NewFiberApp()
	telegramService := NewTelegramService()
	logger := NewLoggerWithTelegram(telegramService)
	redisClient := service.NewRedisClient()
	oracleService, err := service.NewOracleService()
	if err != nil {
		return nil, err
	}
	productRepository := repository.NewProductPriceOracleRepository(oracleService, logger, redisClient)
	tokenUsecase := usecase.NewTokenUsecase(redisClient, logger)
	tokenHandler := http.NewTokenHandler(tokenUsecase, logger)
	configConfig, err := config.Load()
	if err != nil {
		return nil, err
	}
	balanceRepository := repository.NewBalanceOracleRepository(oracleService, logger)
	balanceUsecase := usecase.NewBalanceUsecase(configConfig, logger, balanceRepository)
	balanceHandler := http.NewBalanceHandler(balanceUsecase, logger)
	postgresService, err := service.NewPostgresService(logger)
	if err != nil {
		return nil, err
	}
	rabbitMQService, err := service.NewRabbitMQService()
	if err != nil {
		return nil, err
	}
	ultimaService := service.NewUltimaService(logger)
	healthCheckUsecase := usecase.NewHealthCheckUsecase(logger, redisClient, postgresService, oracleService, rabbitMQService, ultimaService)
	healthCheckHandler := http.NewHealthCheckHandler(healthCheckUsecase, logger)
	postgresInquiryRepository := repository.NewPostgresInquiryRepository(postgresService, logger)
	cutOffRepository := repository.NewCutOffOracleRepository(oracleService, logger)
	errorMessageMappingRepository := repository.NewErrorMappingPostgresRepository(postgresService, logger)
	inquiryUsecase := usecase.NewInquiryUsecase(configConfig, logger, redisClient, productRepository, ultimaService, postgresInquiryRepository, cutOffRepository, errorMessageMappingRepository)
	inquiryHandler := http.NewInquiryHandler(inquiryUsecase, logger)
	preorderRepository := repository.NewPreorderOracleRepository(oracleService, logger, redisClient)
	postgresPaymentRepository := repository.NewPostgresPaymentRepository(postgresService, logger)
	paymentUsecase := usecase.NewPaymentUsecase(configConfig, logger, redisClient, productRepository, preorderRepository, cutOffRepository, postgresInquiryRepository, postgresPaymentRepository, errorMessageMappingRepository, rabbitMQService)
	paymentHandler := http.NewPaymentHandler(paymentUsecase, logger)
	checkStatusUsecase := usecase.NewCheckStatusUsecase(logger, postgresPaymentRepository)
	checkStatusHandler := http.NewCheckStatusHandler(checkStatusUsecase, logger)
	errorMappingHandler := http.NewErrorMappingHandler(logger, errorMessageMappingRepository)
	cryptoServices, err := NewCryptoServices()
	if err != nil {
		return nil, err
	}
	cryptoService := NewCryptoServiceProvider(cryptoServices)
	digitalSignatureService := NewDigitalSignatureServiceProvider(cryptoServices)
	decryptSignatureGenerateUsecase := usecase.NewDecryptSignatureGenerateUsecase(cryptoService, digitalSignatureService, logger)
	decryptSignatureGenerateHandler := http.NewDecryptSignatureGenerateHandler(decryptSignatureGenerateUsecase)
	httpLoggingRepository := repository.NewHTTPLoggingRepository(postgresService, logger)
	handler := NewHandlerWithCrypto(logger, redisClient, productRepository, tokenHandler, balanceHandler, healthCheckHandler, inquiryHandler, paymentHandler, checkStatusHandler, errorMappingHandler, decryptSignatureGenerateHandler, httpLoggingRepository, tokenUsecase, cryptoServices)
	schedulerService := service.NewSchedulerService(logger)
	cleanupRepository := repository.NewCleanupPostgresRepository(postgresService, logger)
	cleanupUsecase := usecase.NewCleanupUsecase(cleanupRepository, logger)
	scheduledJobsUsecase := usecase.NewScheduledJobsUsecase(schedulerService, cleanupUsecase, postgresService, logger)
	callbackLoggingRepository := repository.NewCallbackLoggingRepository(postgresService, logger)
	callbackUsecase := NewCallbackUsecaseWithDeps(rabbitMQService, logger, cryptoService, digitalSignatureService, callbackLoggingRepository, postgresPaymentRepository)
	appContainer := NewAppContainer(app, handler, logger, redisClient, oracleService, postgresService, ultimaService, productRepository, cryptoServices, schedulerService, cleanupUsecase, scheduledJobsUsecase, callbackUsecase, rabbitMQService)
	return appContainer, nil
}

// wire.go:

// ProviderSet groups providers together
var ProviderSet = wire.NewSet(config.Load, NewTelegramService,
	NewLoggerWithTelegram, service.NewRedisClient, service.NewOracleService, service.NewPostgresService, service.NewUltimaService, service.NewSchedulerService, service.NewRabbitMQService, NewCryptoServices,
	NewCryptoServiceProvider,
	NewDigitalSignatureServiceProvider, repository.NewProductPriceOracleRepository, repository.NewBalanceOracleRepository, repository.NewCutOffOracleRepository, repository.NewPostgresInquiryRepository, repository.NewPostgresPaymentRepository, repository.NewErrorMappingPostgresRepository, repository.NewPreorderOracleRepository, repository.NewHTTPLoggingRepository, repository.NewCallbackLoggingRepository, repository.NewCleanupPostgresRepository, usecase.NewTokenUsecase, usecase.NewHealthCheckUsecase, usecase.NewBalanceUsecase, usecase.NewInquiryUsecase, usecase.NewPaymentUsecase, usecase.NewCheckStatusUsecase, usecase.NewCleanupUsecase, usecase.NewScheduledJobsUsecase, usecase.NewDecryptSignatureGenerateUsecase, NewCallbackUsecaseWithDeps, http.NewTokenHandler, http.NewHealthCheckHandler, http.NewBalanceHandler, http.NewInquiryHandler, http.NewPaymentHandler, http.NewCheckStatusHandler, http.NewErrorMappingHandler, http.NewDecryptSignatureGenerateHandler, NewHandlerWithCrypto,

	NewFiberApp,
)

// CryptoServices holds the crypto-related services
type CryptoServices struct {
	DigitalSignatureService service.DigitalSignatureService
	CryptoService           service.CryptoService
}

// NewCryptoServices creates crypto services with loaded keys
func NewCryptoServices() (*CryptoServices, error) {
	privKey, pubKey, err := initKeys()
	if err != nil {
		return nil, err
	}

	rsaPrivKey, ok := privKey.(*rsa.PrivateKey)
	if !ok {
		return nil, fmt.Errorf("private key is not RSA type")
	}
	rsaPubKey, ok := pubKey.(*rsa.PublicKey)
	if !ok {
		return nil, fmt.Errorf("public key is not RSA type")
	}

	digitalSignatureService := service.NewDigitalSignatureService(rsaPrivKey, rsaPubKey)
	cryptoService := service.NewCryptoService(rsaPrivKey, rsaPubKey)

	return &CryptoServices{
		DigitalSignatureService: digitalSignatureService,
		CryptoService:           cryptoService,
	}, nil
}

// initKeys loads RSA keys from environment variables
func initKeys() (interface{}, interface{}, error) {
	privKey, err := utils.LoadPrivateKeyFromString(utils.GetEnv("PRIVATE_KEY", ""))
	if err != nil {
		return nil, nil, err
	}
	pubKey, err := utils.LoadPublicKeyFromString(utils.GetEnv("PUBLIC_KEY", ""))
	if err != nil {
		return nil, nil, err
	}
	return privKey, pubKey, nil
}

// AppContainer holds all application dependencies
type AppContainer struct {
	App                  *fiber.App
	Handler              *http.Handler
	Logger               service.Logger
	RedisClient          service.RedisClient
	OracleService        service.OracleService
	PostgresService      service.PostgresService
	UltimaService        domain.UltimaService
	ProductRepo          domain.ProductRepository
	CryptoServices       *CryptoServices
	SchedulerService     service.SchedulerService
	CleanupUsecase       usecase.CleanupUsecase
	ScheduledJobsUsecase usecase.ScheduledJobsUsecase
	CallbackUsecase      domain.CallbackUsecase
	RabbitMQService      service.RabbitMQService
}

// NewFiberApp creates a new Fiber app
func NewFiberApp() *fiber.App {
	return fiber.New()
}

// NewHandlerWithCrypto creates a new HTTP handler with all sub-handlers and crypto services
func NewHandlerWithCrypto(
	logger service.Logger,
	redisClient service.RedisClient,
	productRepo domain.ProductRepository,
	tokenHandler *http.TokenHandler,
	balanceHandler *http.BalanceHandler,
	healthCheckHandler *http.HealthCheckHandler,
	inquiryHandler *http.InquiryHandler,
	paymentHandler *http.PaymentHandler,
	checkStatusHandler *http.CheckStatusHandler,
	errorMappingHandler *http.ErrorMappingHandler,
	cryptoHandler *http.DecryptSignatureGenerateHandler,
	httpLoggingRepo domain.HTTPLoggingRepository,
	tokenUsecase domain.TokenUsecase,
	cryptoServices *CryptoServices,
) *http.Handler {
	return http.NewHandler(
		logger,
		redisClient,
		cryptoServices.DigitalSignatureService,
		cryptoServices.CryptoService,
		productRepo,
		tokenHandler,
		balanceHandler,
		healthCheckHandler,
		inquiryHandler,
		paymentHandler,
		checkStatusHandler,
		errorMappingHandler,
		cryptoHandler,
		httpLoggingRepo,
		tokenUsecase,
	)
}

// NewAppContainer creates a new AppContainer with all dependencies
func NewAppContainer(
	app *fiber.App,
	handler *http.Handler,
	logger service.Logger,
	redisClient service.RedisClient,
	oracleService service.OracleService,
	postgresService service.PostgresService,
	ultimaService domain.UltimaService,
	productRepo domain.ProductRepository,
	cryptoServices *CryptoServices,
	schedulerService service.SchedulerService,
	cleanupUsecase usecase.CleanupUsecase,
	scheduledJobsUsecase usecase.ScheduledJobsUsecase,
	callbackUsecase domain.CallbackUsecase,
	rabbitMQService service.RabbitMQService,
) *AppContainer {
	return &AppContainer{
		App:                  app,
		Handler:              handler,
		Logger:               logger,
		RedisClient:          redisClient,
		OracleService:        oracleService,
		PostgresService:      postgresService,
		UltimaService:        ultimaService,
		ProductRepo:          productRepo,
		CryptoServices:       cryptoServices,
		SchedulerService:     schedulerService,
		CleanupUsecase:       cleanupUsecase,
		ScheduledJobsUsecase: scheduledJobsUsecase,
		CallbackUsecase:      callbackUsecase,
		RabbitMQService:      rabbitMQService,
	}
}

// NewTelegramService creates a new Telegram service with credentials from environment
func NewTelegramService() service.TelegramService {

	botToken := utils.GetEnv("TELEGRAM_BOT_TOKEN", "")
	chatID := utils.GetEnv("TELEGRAM_CHAT_ID", "")

	return service.NewTelegramService(botToken, chatID)
}

// NewLoggerWithTelegram creates a logger with Telegram error alerting
func NewLoggerWithTelegram(telegramService service.TelegramService) service.Logger {
	return service.NewLoggerWithTelegram(telegramService)
}

// NewCryptoServiceProvider extracts CryptoService from CryptoServices
func NewCryptoServiceProvider(cryptoServices *CryptoServices) service.CryptoService {
	return cryptoServices.CryptoService
}

// NewDigitalSignatureServiceProvider extracts DigitalSignatureService from CryptoServices
func NewDigitalSignatureServiceProvider(cryptoServices *CryptoServices) service.DigitalSignatureService {
	return cryptoServices.DigitalSignatureService
}

// NewCallbackUsecaseWithDeps creates a callback usecase with all required dependencies
func NewCallbackUsecaseWithDeps(
	rabbitMQService service.RabbitMQService,
	logger service.Logger,
	cryptoService service.CryptoService,
	digitalSignatureService service.DigitalSignatureService,
	callbackLoggingRepository domain.CallbackLoggingRepository,
	postgresPaymentRepo domain.PostgresPaymentRepository,
) domain.CallbackUsecase {
	return usecase.NewCallbackUsecase(
		rabbitMQService,
		logger,
		cryptoService,
		digitalSignatureService,
		callbackLoggingRepository,
		postgresPaymentRepo,
	)
}
