package constanta

const OS_ENV_LOG_DIR = "LOG_DIR"
const OS_ENV_TIME_JOB_CLEAR_LOG = "TIME_JOB_CLEAR_LOG"
const OS_ENV_URL_RABBIT_MQ = "URL_RABBIT_MQ"
const OS_ENV_QUEUE_NAME = "QUEUE_NAME"
const OS_ENV_URL_CONNECTION = "URL_CONNECTION"
const OS_ENV_TokenBotTelagram = "TokenBotTelagram"
const OS_ENV_ChatId = "ChatId"
const OS_ENV_Env = "Env"
const OS_ENV_PORT = "PORT"
const OS_ENV_DB_POOL_MAX_OPEN_CONNS = "DB_POOL_MAX_OPEN_CONNS"
const OS_ENV_DB_POOL_MAX_IDLE_CONNS = "DB_POOL_MAX_IDLE_CONNS"
const OS_ENV_DB_POOL_CONN_MAX_LIFETIME = "DB_POOL_CONN_MAX_LIFETIME"
const OS_ENV_DB_POOL_CONN_MAX_IDLE_TIME = "DB_POOL_CONN_MAX_IDLE_TIME"

const FAILED_STATUS string = "1"

const FLAG_SUCCESS_CONSUME string = "10"
const FLAG_FAILED_CONSUME string = "-1"

// Publisher-Provider HTTP client config
const OS_ENV_PUBLISHER_PROVIDER_BASE_URL = "PUBLISHER_PROVIDER_BASE_URL"
const OS_ENV_PUBLISHER_PROVIDER_TIMEOUT = "PUBLISHER_PROVIDER_TIMEOUT"
const OS_ENV_PUBLISHER_PROVIDER_MAX_RETRIES = "PUBLISHER_PROVIDER_MAX_RETRIES"
